apiVersion: batch/v1
kind: Job
metadata:
  name: snyk-reconciler
  namespace: snyk-reconciler
spec:
  template:
    spec:
      serviceAccountName: snyk-reconciler
      containers:
      - image: <YourCreatedImage>
        name: snyk-reconciler
        resources: {}
        imagePullPolicy: Always
        securityContext:
          privileged: True
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: SNYK_TOKEN
        - name: SNYK_CFG_ORG_ID
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: SNYK_CFG_ORG_ID
        - name: SNYKAPIVERSION
          value: "2023-11-06~beta"
        - name:  SNYKDEBUG
          value: "False"
        volumeMounts:
        - mountPath: /tmp/.docker
          name: snyk-creds
      restartPolicy: Never
      volumes:
      - name: docker-config
        secret:
          defaultMode: 420
          items:
          - key: dockercfg.json
            path: config.json
          optional: true
          secretName: snyk-creds
